### ISSUE TITLE
Update Team

### ISSUE THREAD

**Issue by shreshthagarwal** [EduTech-official/EduWeb#12]
Update the team details as seen on https://eduminerva.live/team

### Instructions:

1. Fork the repository
2. Clone your forked version locally
3. Go to src/Config/Team/index.js
4. Update the names, designations and picture links
5. Commit the changes
6. Create a Pull Request

**Comment by 27Adityasahil** [comment]
Hello @shreshthagarwal !

**Comment by prashantrai-30** [comment]
Hey @shreshthagarwal ,can you assign this issue to me,I have a potential solution for this.
